name: Hello World!

on:
  push:
    branches:
      - main
      # note that your "main" branch might be called main instead of master
# defaults:
#   run:
#     working-directory: ./CI-CD/pokedex
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
