name: Setup

on:
  push:
    branches:
      - main

jobs:
  sample_deployment_pipeline:
    runs-on: ubuntu-20.04
    defaults:
      run: 
        working-directory: ci-cd/part11
    steps:
        - uses: actions/checkout@v3

        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
              pokedex:
                - 'pokedex/**'

        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: '16'

        - name: install dependencies
          run: npm install

        - name: check style (eslint)
          if: steps.filter.outputs.changes == 'true'
          run: npm run eslint

